# Generated by Django 4.0.5 on 2022-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='coooking_order',
            field=models.TextField(default='a', help_text='describe how the recipe should be cooked', max_length=1000, verbose_name='cooking order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='a', help_text='add a short description of the recipe', max_length=1000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'grams'), ('u', 'units'), ('ts', 'teaspoons'), ('tbls', 'table spoons'), ('c', 'cups')], default='g', max_length=4, verbose_name='measured in'),
        ),
    ]
