# Generated by Django 4.0.5 on 2022-06-17 09:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0002_recipe_coooking_order_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('kg', 'kilograms'), ('g', 'grams'), ('l', 'liters'), ('ml', 'mililiters'), ('u', 'units'), ('ts', 'teaspoons'), ('tbls', 'table spoons'), ('c', 'cups')], default='g', max_length=4, verbose_name='measured in'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='coooking_order',
            field=tinymce.models.HTMLField(help_text='describe how the recipe should be cooked', verbose_name='cooking order'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
