# Generated by Django 4.0.5 on 2022-06-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0004_rename_coooking_order_recipe_cooking_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('kg', 'kilograms'), ('g', 'grams'), ('l', 'liters'), ('ml', 'mililiters'), ('units', 'units'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('c', 'cups')], default='g', max_length=4, verbose_name='measured in'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_site.recipe'),
        ),
    ]
