# Generated by Django 4.0.5 on 2022-06-20 12:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_site', '0005_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipe',
            unique_together={('user', 'recipe')},
        ),
    ]
