# Generated by Django 4.0.5 on 2022-06-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0006_alter_userrecipe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipes', to='recipe_site.recipe'),
        ),
    ]
