# Generated by Django 4.0.5 on 2022-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0007_alter_userrecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='enter ingredient name (in plural form if possible)', max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
