# Generated by Django 4.0.5 on 2022-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0010_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='note',
            field=models.TextField(blank=True, help_text='add a private note to yourself about this recipe', max_length=1000, null=True, verbose_name='private note'),
        ),
    ]
